- name: synchronize time
  command: /sbin/hwclock --systohc

- name: refresh locales
  command: /usr/sbin/locale-gen

- name: reload fail2ban
  service: name=fail2ban state=reloaded

- name: reload snmpd
  service: name=snmpd state=reloaded
