- name: synchronize time
  command: /sbin/hwclock --systohc

- name: refresh locales
  command: /usr/sbin/locale-gen

- name: reload fail2ban
  service: name=fail2ban state=reloaded

- name: restart snmpd
  service: name=snmpd state=restarted

- name: register snmpd
  delegate_to: "{{ master.mrtg }}"
  command: /etc/mrtg/acrnew.sh {{ inventory_hostname }}

