- name: postgresql repository key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: postgresql repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main"

- name: postgresql access
  copy: src=etc/postgresql/9.3/main/pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
  notify:
    - restart postgresql

- name: postgresql access
  template: src=etc/postgresql/9.3/main/postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf
  notify:
    - restart postgresql

- name: postgresql packages
  apt: name={{ item }}
  with_items:
    - postgresql-9.3
    - python-psycopg2

- name: postgresql root user
  postgresql_user: name=admin password={{ mysql.root_password }} role_attr_flags=SUPERUSER,LOGIN

- name: install psql utilities
  copy: src=usr/local/sbin dest=/usr/local

- name: enable daily backups
  cron: name="backup all databases" hour=0 minute=43 job=/usr/local/sbin/psqldump cron_file=dumpalldb user=root

