- name: postgresql repository key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: postgresql repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main"

- name: postgresql packages
  apt: name=postgresql-9.3

