- include: mariadb.yml
  when: mariadb|default(False)

- include: mysql.yml
  when: not mariadb|default(False)

- name: install mysql common packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - python-mysqldb

- name: customize mysql config
  copy: src={{ item }} dest=/etc/mysql/conf.d/general.cnf
  with_first_found:
    - etc/mysql/conf.d/general.cnf.{{ inventory_hostname }}
    - etc/mysql/conf.d/general.cnf.{{ ansible_distribution_version }}
    - etc/mysql/conf.d/general.cnf
  notify:
    - reload mysql

- name: write back the default config - temporary
  copy: src=etc/mysql/my.cnf.{{ ansible_distribution_version }} dest=/etc/mysql/my.cnf
  notify:
    - reload mysql

- name: clean the default config - temporary
  file: path=/etc/mysql/my.cnf.dpkg-dist state=absent
  notify:
    - reload mysql

- name: rotate error logs
  lineinfile: dest=/etc/logrotate.d/mysql-server regexp="^/var/log/mysql.log" line="/var/log/mysql.log /var/log/mysql/mysql.log /var/log/mysql/mysql-slow.log /var/log/mysql/error.log {"
  ignore_errors: yes

- name: create root user
  mysql_user: name=root password={{ mysql.root_password }}

- name: allow root to login
  copy:
    content: |
      [client]
      user=root
      password={{ mysql.root_password }}
    dest: /root/.my.cnf
    mode: 600

- name: create hosting database
  mysql_db: name=hosting

- name: create hosting user
  mysql_user: name=hosting password={{ mysql.hosting_password }} priv=hosting.*:ALL

- name: create creator user
  mysql_user: name=creator host={{ mysql.creator_host }} password={{ mysql.creator_password }} priv=*.*:ALL,GRANT state=present

- name: install mysql utilities
  copy: src=usr/local/sbin dest=/usr/local

- name: if file exist
  stat: path=/usr/local/sbin/dumpalldb
  register: st

- name: set execute
  file: path=/usr/local/sbin/dumpalldb state=touch mode=755
  when: st.stat.exists

- name: enable daily backups
  cron: name="backup all databases" hour=0 minute=43 job=/usr/local/sbin/dumpalldb cron_file=dumpalldb user=root

- name: set cron mail
  lineinfile: dest=/etc/cron.d/dumpalldb insertbefore='BOF' line='MAILTO=info@tele3.cz'
          
          
