---
- hosts: telemail
  vars:
    virtualenv: /home/hosting/telemail
    user: hosting
  vars_prompt:
    admin_password: Admin password
  roles:
    - common
    - users
    - cert
    - telemail
    - php-fpm
    - roundcube
    - nginx
    - exim
    - exim-spam
    - dovecot
