- hosts: webhosting
  vars:
    owner: pureftpd.owner|default('www-data')
  roles:
#    - common
#    - cert
#    - exim
#    - mysql
#    - apache
    - php
#    - phpmyadmin
#    - pureftpd
#    - rsync
