- hosts: webhosting
  vars:
    owner: "{{ pureftpd_owner|default('www-data') }}"
  roles:
    - common
    - users
    - cert
    - exim
    - mysql
    - apache
    - php
    - phpmyadmin
    - pureftpd
    - rsync
