- name: remove example configs
  file: path={{ item }} state=absent
  with_items:
    - /etc/apache2/sites-enabled/000-default
    - /etc/apache2/conf.d/other-vhosts-access-log

- name: apache custom configs     
  copy: src={{ item }} dest=/etc/apache2/conf.d/{{ item.rsplit('/', 1)[-1].split('.', 1)[0] }}.conf
  with_fileglob:
    - etc/apache2/conf.d/*
  when: not item.endswith('.2.4')
  notify:
    - restart apache

- name: apache site config
  template: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/apache2/sites-available/default
    - etc/apache2/sites-available/ssl
