- name: remove example configs
  file: path={{ item }} state=absent
  with_items:
    - /etc/apache2/sites-enabled/000-default.conf
    - /etc/apache2/sites-available/000-default.conf
    - /etc/apache2/sites-enabled/default-ssl.conf
    - /etc/apache2/sites-available/default-ssl.conf
    - /etc/apache2/conf-enabled/other-vhosts-access-log.conf
    - /etc/apache2/conf-available/other-vhosts-access-log.conf
    - /etc/apache2/conf-enabled/serve-cgi-bin.conf
    - /etc/apache2/conf-available/serve-cgi-bin.conf

- name: apache custom config
  copy: src={{ item }} dest=/etc/apache2/conf-enabled/{{ item|basename }}.conf
  with_fileglob:
    - etc/apache2/conf.d/*
  notify:
    - restart apache

- name: enable apache ssl dependency modules
  apache2_module: name=socache_shmcb
  notify:
    - reload apache

- name: apache site config
  template: src={{ item }} dest=/{{ item }}.conf
  with_items:
    - etc/apache2/sites-available/default
    - etc/apache2/sites-available/ssl

