- name: apache custom configs
  copy: src={{ item }} dest=/etc/apache2/conf-enabled/{{ item.rsplit('/', 1)[-1].split('.', 1)[0] }}.conf
  with_fileglob:
    - etc/apache2/conf.d/*
  when: not item.endswith('.2.2')
  notify:
    - restart apache
