- name: apache packages
  apt: name={{ item }}
  with_items:
    - apache2
    - apache2-mpm-prefork
    - cronolog
    - openssl
    - ca-certificates      

- name: installed apache version
  shell: "dpkg -p apache2 | sed -n 's/^Version: \\([0-9]*:\\)*\\([0-9]*\\.[0-9]*\\).*/\\2/p'"
  register: installed_version

- name: apache port config
  copy: src=etc/apache2/ports.conf dest=/etc/apache2
  notify:
    - restart apache

- name: apache static mod config
  copy: src=etc/apache2/mods-available dest=/etc/apache2
  notify:
    - restart apache

- include: 2.2.yml
  when: installed_version.stdout|version_compare('2.4', '<')
  
- include: 2.4.yml
  when: installed_version.stdout|version_compare('2.4', '>=')

- name: enable apache modules
  apache2_module: name=ssl
  notify:
    - reload apache

- name: enable apache sites
  command: a2ensite {{ item }}
  with_items:
    - default
    - ssl
  notify:
    - reload apache
