- name: apache packages
  apt: name={{ item }}
  with_items:
    - apache2
    - apache2-mpm-prefork
    - cronolog
    - openssl
    - ca-certificates      

- name: enable SSL dependency modules
  apache2_module: name=socache_shmcb
  when: ansible_distribution_version|version_compare('14.04', '>=')

- name: apache static config
  copy: src=etc/apache2 dest=/etc
  notify:
    - reload apache

- name: apache template config
  template: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/apache2/sites-available/ssl
  notify:
    - reload apache

- name: apache link config
  file: src=../{{ item }} dest=/etc/apache2/{{ item|replace('available', 'enabled') }} state=link force=yes
  with_items:
    - mods-available/ssl.conf
    - mods-available/ssl.load
    - sites-available/ssl
  notify:
    - reload apache

- name: remove wrong apache config
  file: path=/etc/apache2/conf.d/other-vhosts-access-log state=absent
  notify:
    - reload apache

