- name: unpack zkt source
  unarchive: src=zkt-1.1.3.tar.gz dest=/tmp creates=/tmp/zkt-1.1.3

- name: configure zkt
  command: ./configure chdir=/tmp/zkt-1.1.3 creates=/tmp/zkt-1.1.3/config.h

- name: make zkt
  command: make chdir=/tmp/zkt-1.1.3 creates=/tmp/zkt-1.1.3/zkt-signer

- name: install zkt
  command: make install chdir=/tmp/zkt-1.1.3 creates=/usr/local/bin/zkt-signer


