- name: fail2ban repository
  apt_repository: repo="ppa:leonbo/fail2ban"
  when: ansible_lsb.major_release|int < 14

- name: fail2ban packages
  apt: name={{ item }}
  with_items:
    - python-pyinotify
    - fail2ban

- name: Check to see if /var/log/messages exists
  stat: path=/var/log/messages
  register: messages_conf

- name: fail2ban config
  template: src={{ item }} dest=/etc/fail2ban/jail.local
  with_first_found:
    - ../templates/etc/fail2ban/jail.local.{{ inventory_hostname }}
    - ../templates/etc/fail2ban/jail.local
  notify:
    - reload fail2ban

- name: fail2ban filters
  copy: src=etc/fail2ban/filter.d dest=/etc/fail2ban
  notify:
    - reload fail2ban

