- name: update sources list
  template: src=etc/apt/sources.list dest=/etc/apt/sources.list

- name: remove obsolete ppas
  file: name=/etc/apt/sources.list.d/{{ item[0] }}.list{{ item[1] }} state=absent
  with_nested:
    -
      - jbar-comoga-oneiric
      - nginx-development-oneiric
      - karmic
      - rdiff-backup
      - uwsgi-release-oneiric
    - ['', '.save']

- name: add mosh PPA
  apt_repository: repo='ppa:keithw/mosh' update_cache=no
  when: ansible_lsb.major_release|int < 14

- name: install useful packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - patch
    - iotop
    - iftop
    - htop
    - mytop
    - saidar
    - ifstat
    - dstat
    - unp
    - mosh
    - nethogs
    - ngrep
    - python-software-properties
    - ca-certificates
    - multitail
    - whois
    - curl
    - lftp
    - ipython
    - rdiff-backup
    - socat
    - pv
    - python-dev
    - python-pip
    - python-virtualenv
    - git

- name: remove conflicting packages
  apt: name={{ item }} state=absent
  with_items:
    - wireless-tools
