- name: snmp packages
  apt: name=snmpd
  with_items:
    - "{% if ansible_lsb.major_release|int < 14 %}snmp{% else %}libsnmp30{% endif %}"
    - snmpd

- name: snmp config
  template: src=etc/snmp/snmpd.conf dest=/etc/snmp/snmpd.conf
  notify:
    - restart snmpd

- name: register snmpd
  delegate_to: "{{ master.mrtg }}"
  command: /etc/mrtg/acrnew.sh  {{ inventory_hostname.replace('.', '') }}  {{ inventory_hostname }} 

- name: update snmpd
  delegate_to: "{{ master.mrtg }}"
  command: /etc/mrtg/aupdnet.sh  {{ inventory_hostname.replace('.', '') }} 


