- name: snmp packages
  apt: name={{ item }}
  with_items:
    - snmp
    - snmpd
  notify:
    - register snmp

- name: snmp config
  template: src=etc/snmp/snmpd.conf dest=/etc/snmp/snmpd.conf
  notify:
    - restart snmpd
