- name: disable ssh access with passwords
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^#?PasswordAuthentication"
    line="PasswordAuthentication no"
  notify:
    - reload ssh

- name: allow ssh users
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^#?AllowUsers"
    line="AllowUsers {{ users|selectattr('default', 'defined')|selectattr('default')|join(' ', attribute='username') }} {{ admins|default([])|join(' ') }} root@{{ hub.ipv4 }} root@{{ hub.ipv6 }}"
  notify:
    - reload ssh
