- name: exim packages
  apt: name={{ item }}
  with_items:
    - exim4-daemon-heavy
    - heirloom-mailx
    - ssl-cert

- name: SSL Debian-exim permissions
  user: name=Debian-exim groups=ssl-cert append=yes

- name: SSL directory permissions
  file: path=/etc/ssl/private mode=711

- name: customize exim4.conf
  template: src=etc/exim4/exim4.conf{% if 'mailer' in group_names %}.mailer{% elif 'telemail' in group_names %}.telemail{% endif %} dest=/etc/exim4/exim4.conf mode=644
  notify:
    - reload exim

- name: DKIM key
  copy: src=/etc/ssl/private/dkim.tele3.cz.key dest=/etc/ssl/private/dkim.tele3.cz.key owner=root group=Debian-exim mode=640
  when: '"telemail" in group_names'
