- name: roundcube repository
  apt_repository: repo=ppa:tuxpoldo/roundcube

- name: roundcube packages
  apt: name={{ item }}
  with_items:
    - roundcube-sqlite3
    - roundcube
    - roundcube-plugins
    - memcached

- name: disable apache
  service: name=apache2 state=stopped enabled=no

- name: roundcube database file
  copy: src=var/lib/roundcube dest=/var/lib owner=www-data group=www-data

- name: roundcube config files
  copy: src=etc/roundcube dest=/etc owner=root group=www-data mode=0640

- name: roundcube plugins
  copy: src=usr/share/roundcube/plugins dest=/usr/share/roundcube

- name: symlink plugins
  file: src=/usr/share/roundcube/plugins/{{ item|basename }} dest=/var/lib/roundcube/plugins/{{ item|basename }} state=link
  with_dirglob:
    - /usr/share/anstele/roles/roundcube/files/usr/share/roundcube/plugins/*
