- include: php5.2.yml
  when: php_version|default == '5.2'

- include: php5.4.yml
  when: php_version|default == '5.4'

- include: php5.4.20.yml
  when: php_version|default == '5.4.20'

- name: PHP packages for 12.10
  apt: name=db4.8-util
  when: ansible_distribution_version == "12.10"

- name: PHP packages
  apt: name={{ item }}
  with_items:
      - libapache2-mod-php5
      - php5-gd
      - php5-mcrypt
      - php5-mysql
      - php5-xsl
      - php5-curl

- name: PHP non-5.2 packages
  apt: name={{ item }}
  with_items:
      - php5-imap
      - php5-xmlrpc
  when: php_version|default == '5.2'

- name: installed apache version
  shell: "dpkg -p apache2 | sed -n 's/^Version: \\([0-9]*:\\)*\\([0-9]*\\.[0-9]*\\).*/\\2/p'"
  register: apache_installed_version

- name: installed PHP version
  shell: "dpkg -p libapache2-mod-php5 | sed -n 's/^Version: \\([0-9]*:\\)*\\([0-9]*\\.[0-9]*\\).*/\\2/p'"
  register: php_installed_version

- name: PHP config
  copy: src=etc dest=/
  notify:
    - reload apache

- include: apache2.2.yml
  when: apache_installed_version.stdout|version_compare('2.4', '<')

- include: apache2.4.yml
  when: apache_installed_version.stdout|version_compare('2.4', '>=')

- name: PHP custom configs for Apache 2.4
  template: src={{ item }} dest=/etc/apache2/conf-enabled/{{ item|basename }}.conf
  with_fileglob:
    - ../custom/{{ inventory_hostname }}/*
  when: apache_installed_version.stdout|version_compare('2.4', '>=')
  notify:
    - restart apache

- name: apache module config
  template: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/apache2/mods-available/rewrite.conf

- name: enable apache modules
  apache2_module: name=rewrite
  notify:
    - restart apache

#- name: revert PHP main config
#  copy: src=../global/php.ini.{{ php_installed_version.stdout }} dest=/etc/php5/apache2/php.ini
#  notify:
#    - reload apache

- name: customize PHP main config
  template: src={{ item }} dest=/etc/php5/apache2/conf.d/php.ini
  with_first_found:
    - ../global/{{ inventory_hostname }}
    - ../global/base.ini.{{ php_installed_version.stdout }}
    - ../global/base.ini
  notify:
    - reload apache

- name: default site
  copy: src=var/www/default dest=/var/www

- name: PHP maintenance scripts
  copy: src={{ item }} dest=/{{ item }} mode=755
  with_items:
    - usr/local/sbin/chroot-php
    - usr/local/bin/phpmail

- name: mail log
  file: path=/var/log/phpmail.log owner=www-data group=www-data state=touch
