
- name: phpmyadmin packages
  apt: name=phpmyadmin

- name: create phpmyadmin db
  shell: "echo 'CREATE DATABASE IF NOT EXISTS `phpmyadmin` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;' | mysql "

- name: create phpmyadmin db tables
  shell: "mysql phpmyadmin < /usr/share/dbconfig-common/data/phpmyadmin/install/mysql "

- name: installed apache version
  shell: "dpkg -p apache2 | sed -n 's/^Version: \\([0-9]*:\\)*\\([0-9]*\\.[0-9]*\\).*/\\2/p'"
  register: apache_installed_version

- name: phpmyadmin static config
  copy: src=etc/apache2/conf.d/phpmyadmin dest=/etc/apache2/{% if apache_installed_version.stdout|version_compare('2.4', '<') %}conf.d/phpmyadmin{% else %}conf-enabled/phpmyadmin.conf{% endif %}
  notify:
    - reload apache

- name: phpadmin db config
  template: src=etc/phpmyadmin/config-db.php dest=/etc/phpmyadmin/config-db.php
  notify:
    - reload apache
