- name: pureftpd packages
  apt: name=pure-ftpd

- name: pureftpd static config
  copy: src=etc/pure-ftpd/conf dest=/etc/pure-ftpd
  notify:
    - reload pureftpd

- name: pureftpd authentication
  file: src=../conf/PureDB dest=/etc/pure-ftpd/auth/50pure state=link
  notify:
    - reload pureftpd

- name: pureftpd accounts
  template: src=etc/pure-ftpd/pureftpd.passwd dest=/etc/pure-ftpd/pureftpd.passwd
  notify:
    - refresh pureftpd database

- name: data directory
  file: path=/var/www/hosting owner={{ owner }} group={{ owner }} mode=775 state=directory

