- name: create new certificate
  command: "{{ item }} chdir=/etc/ssl"
  delegate_to: 127.0.0.1
  with_items:
    - openssl genrsa -out private/{{ inventory_hostname }}.key 2048
    - openssl req -new -key private/{{ inventory_hostname }}.key -config openssl.cnf -out requests/{{ inventory_hostname }}.csr -subj "/C=CZ/ST=Czech Republic/L=Prague/O=TELE3/OU=Webserver Team/CN={{ inventory_hostname }}/emailAddress=jbar@tele3.cz"
    - openssl ca -config openssl.cnf -in requests/{{ inventory_hostname }}.csr -out certs/{{ inventory_hostname }}.crt -notext -batch
  notify:
    - reload apache
    - reload nginx
    - reload pureftpd-mysql
    - reload pureftpd

- name: upload private key
  copy: src=/etc/ssl/private/{{ inventory_hostname }}.key dest=/etc/ssl/private/{{ inventory_hostname }}.key mode=0600

- name: access the private key
  file: path=/etc/ssl/private/{{ inventory_hostname }}.key mode=644

- name: upload certificate
  copy: src=/etc/ssl/certs/{{ inventory_hostname }}.crt dest=/etc/ssl/certs/{{ inventory_hostname }}.crt

- name: pureftpd certificate
  copy: content="{{ lookup('file', '/etc/ssl/private/' + inventory_hostname + '.key') }}\n{{ lookup('file', '/etc/ssl/certs/' + inventory_hostname + '.crt') }}" dest=/etc/ssl/private/pure-ftpd.pem mode=0600

- name: access the key directory
  file: path=/etc/ssl/private state=directory mode=755
