- name: disable apache
  service: name=apache2 state=stopped enabled=no
  ignore_errors: yes

- name: nginx packages
  apt: name=nginx

- name: customize main nginx config
  copy: src=etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - reload nginx

- name: customize fastcgi params
  template: src=etc/nginx/fastcgi_params dest=/etc/nginx/fastcgi_params

- name: disable the default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - reload nginx

- name: enable sites by group
  template: src={{ item }} dest=/etc/nginx/sites-enabled/{{ item|basename }}
  with_fileglob:
    - ../templates/etc/nginx/sites-enabled/*
  when: item|basename in group_names
  notify:
    - reload nginx

- name: enable site by hostname
  template: src={{ item }} dest=/etc/nginx/sites-enabled/{{ inventory_hostname }}
  with_fileglob: ../templates/etc/nginx/sites-enabled/{{ inventory_hostname }}
  notify:
    - reload nginx

- name: set the log rotation for TELE3 stats
  copy: src=etc/cron.hourly/nginx-logs dest=/etc/cron.hourly/nginx-logs mode=755

- name: modify the log rotation for other logs
  copy: src=etc/logrotate.d/nginx dest=/etc/logrotate.d/nginx
