- name: find owner UID
  command: id -u {{ owner }}
  register: owner_uid

- name: pureftpd accounts
  template: src=etc/pure-ftpd/pureftpd.passwd dest=/etc/pure-ftpd/pureftpd.passwd
  notify:
    - refresh pureftpd database
